# Generated by Django 5.2.14 on 2026-05-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterAreaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.PositiveIntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app.waterarea')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
