# Generated by Django 5.2.14 on 2026-05-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_waterarea_waterareapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_type', models.CharField(choices=[('none', 'Чистая вода'), ('light', 'Лёгкий лёд'), ('medium', 'Средний лёд'), ('heavy', 'Тяжёлый лёд')], default='none', max_length=20)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_zones', to='app.waterarea')),
            ],
        ),
    ]
