# Generated by Django 5.2.14 on 2026-05-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ship_ice_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ship',
            name='ice_class',
        ),
        migrations.CreateModel(
            name='IceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_type', models.CharField(choices=[('none', 'Открытая вода'), ('light', 'Молодой лёд'), ('heavy', 'Толстый лёд')], default='none', max_length=20)),
                ('lat_min', models.FloatField()),
                ('lat_max', models.FloatField()),
                ('lon_min', models.FloatField()),
                ('lon_max', models.FloatField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ice_conditions', to='app.waterarea')),
            ],
        ),
        migrations.CreateModel(
            name='IceImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice_type', models.CharField(max_length=20)),
                ('coefficient', models.FloatField()),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='app.shiptype')),
            ],
            options={
                'unique_together': {('ship_type', 'ice_type')},
            },
        ),
        migrations.AddField(
            model_name='ship',
            name='ship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shiptype'),
        ),
        migrations.DeleteModel(
            name='IceZone',
        ),
    ]
